# See: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

require:
 - 'rubocop-rails'
 - 'test_prof/rubocop'

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/*.rb'
  Exclude:
    - 'Capfile'
    - 'log/**/*'
    - 'db/**/*'
    - 'stubs/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'app/views'

  DefaultFormatter: progress
  DisplayCopNames: true

# Checks formatting of special comments
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

########################################
# Style Cops

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# String#format is private now
Style/FormatString:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

########################################
# Layout Cops

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/CaseIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 110
  Exclude:
    - 'app/views/**/*'

########################################
# Naming Cops

Naming/FileName:
  Enabled: false

########################################
# Security Cops

Security/Eval:
  Enabled: true

########################################
# Lint Cops

Lint/AssignmentInCondition:
  Enabled: false

########################################
# Metrics Cops

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 20

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - spec/**/*

########################################
# Bundler Cops

Bundler/OrderedGems:
  Enabled: false

########################################
# Rails Cops

Rails/FilePath:
  EnforcedStyle: arguments

########################################
# TestProf Cops

RSpec/AggregateFailures:
  Enabled: true
  Include:
    - 'spec/**/*.rb'
